services:
  kube-sherlock:
    container_name: kube-sherlock
    restart: "no"
    build:
      context: .
      args:
        DEBUG: "true"
    env_file: .env
    command:
      - "uv"
      - "run"
      - "python"
      - "-Xfrozen_modules=off"
      - "-m"
      - "debugpy"
      - "--listen"
      - "0.0.0.0:5678"
      - "--wait-for-client"
      - "main.py"
    volumes:
      - ./sa:/app/sa
      - kube_config:/root/.kube
    ports:
      - "5678:5678"
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./main.py
          target: /app/main.py
        - action: sync
          path: ./system-prompt.txt
          target: /app/system-prompt.txt
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile

volumes:
  kube_config:
