services:
  mlflow:
    container_name: mlflow
    restart: unless-stopped
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"

  kube-sherlock:
    container_name: kube-sherlock
    restart: unless-stopped
    build:
      context: .
    env_file: .env
    volumes:
      - ./service-account.json:/app/service-account.json
      - kube_config:/root/.kube
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./main.py
          target: /app/main.py
        - action: sync
          path: ./system-prompt.txt
          target: /app/system-prompt.txt
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile

volumes:
  kube_config:
