services:
  redis:
    container_name: redis
    restart: always
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  kube-sherlock:
    container_name: kube-sherlock
    restart: always
    build:
      context: .
    env_file: .env
    volumes:
      - ./service-account.json:/app/service-account.json
      - kube_config:/root/.kube
    depends_on: [redis]
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./main.py
          target: /app/main.py
        - action: sync
          path: ./system-prompt.txt
          target: /app/system-prompt.txt
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile

volumes:
  redis_data:
  kube_config:
