services:
  redis:
    container_name: redis
    restart: always
    image: bitnami/redis:latest
    env_file: .env
    volumes:
      - redis_data:/bitnami/redis/data

  kube-sherlock:
    container_name: kube-sherlock
    restart: always
    build:
      context: .
      args:
        DEBUG: "false"
    env_file: .env
    volumes:
      - ./service-account.json:/app/service-account.json
      - kube_config:/root/.kube
    depends_on: [redis]
    # Uses default CMD from Dockerfile: ["uv", "run", "python", "main.py"]
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./main.py
          target: /app/main.py
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile

volumes:
  redis_data:
  kube_config:
