apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-sherlock
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-sherlock
  template:
    metadata:
      labels:
        app: kube-sherlock
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
        - name: kube-sherlock
          image: ghcr.io/prefeitura-rio/kube-sherlock:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          envFrom:
            - secretRef:
                name: kube-sherlock-secrets
          volumeMounts:
            - name: rj-superapp-staging-sa
              mountPath: /app/sa/rj-superapp-staging_application_us-central1.json
              subPath: rj-superapp-staging_application_us-central1.json
              readOnly: true
            - name: rj-superapp-sa
              mountPath: /app/sa/rj-superapp_application_us-central1.json
              subPath: rj-superapp_application_us-central1.json
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: rj-superapp-staging-sa
          secret:
            secretName: rj-superapp-staging-application-us-central1
        - name: rj-superapp-sa
          secret:
            secretName: rj-superapp-application-us-central1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kube-sherlock
  labels:
    app: kube-sherlock
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: kube-sherlock
