apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-sherlock
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-sherlock
  template:
    metadata:
      labels:
        app: kube-sherlock
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
        - name: kube-sherlock
          image: ghcr.io/prefeitura-rio/kube-sherlock:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          env:
            - name: OTEL_SERVICE_NAME
              value: "kube-sherlock"
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.signoz.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
          envFrom:
            - secretRef:
                name: kube-sherlock-secrets
          volumeMounts:
            - name: gcp-sa-key
              mountPath: /app/service-account.json
              subPath: service-account.json
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
      volumes:
        - name: gcp-sa-key
          secret:
            secretName: gcp-sa-key
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kube-sherlock
  labels:
    app: kube-sherlock
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: kube-sherlock
